gui2: Prevent "control reaches end of non-void function" warning on gcc 4.7
This is a quick fix and mordante should review it later.

gcc 4.7 doesn't seem to be happy with gui2::tplacer_::build()'s switch
statement and appears to expect more cases despite
gui2::tplacer_::tgrow_direction doesn't have more members. The warning
in question:

  src/gui/auxiliary/placer.cpp:43:1: error: control reaches end of non-void function [-Werror=return-type]


Former-commit-id: c90f2b10b7f2e4560f3efd2563d00e5af8c81ade
Former-commit-id: 726b91c8de113919b587f43a8705e89cc0e914b7
Former-commit-id: 76ce337c3ba787011009d53621c7a7f44435f265
Former-commit-id: 9d112b3c6ab6a559f0cea732e723d1290c0f54a5 [formerly 3109fc1f4f0c58175d58923a5fd4e6eee6873edb]
Former-commit-id: 7d94d1acfad143f2763c29e9da915a927e73a3ba