Remove `this` null pointer comparisons
It appears the standard specifies that `this` being null is undefined
behavior. Compilers may choose to optimize taking UB into account; in
particular, the null pointer check in question can be optimized out.
clang 3.5 has a new warning flag -Wtautological-pointer-compare which
warns against that particular case, among others.

http://llvm.org/releases/3.5.0/tools/clang/docs/ReleaseNotes.html

This fixes the following warnings with clang 3.5:

  src/actions/../game_data.hpp:66:5: error: 'this' pointer cannot be null in well-defined C++ code; comparison may be assumed to always evaluate to true [-Werror,-Wtautological-undefined-compare]
  src/actions/../game_data.hpp:74:5: error: 'this' pointer cannot be null in well-defined C++ code; comparison may be assumed to always evaluate to true [-Werror,-Wtautological-undefined-compare]
  src/actions/../game_data.hpp:130:5: error: 'this' pointer cannot be null in well-defined C++ code; comparison may be assumed to always evaluate to true [-Werror,-Wtautological-undefined-compare]


Former-commit-id: f20d1d692613286a2c226d6e7039846f69391e39
Former-commit-id: 3c1088765483c485d11b00f8a7c40f68550d8960
Former-commit-id: 8174ae8c09c33a918e502cf4be11331edd5003d8
Former-commit-id: 9293cd43dab342be42ce46e0a48e6bcb6c076fdc [formerly 6828908c2a911665b73e632e548f71c22cab7640]
Former-commit-id: deef1e2318e37a6bcc46b29c92ddd2fd5842fa33