SConstruct: Do not link with libintl - Wesnoth now uses boost::locale
http://forums.wesnoth.org/viewtopic.php?f=10&p=577648

This fixes compilation error on MinGW:
...
g++ -o wesnothd.exe -mwindows -mthreads build\release\sd... -lboost_locale-mgw49-mt-1_57 -lwsock32 -lintl -lz
../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lintl
collect2.exe: error: ld returned 1 exit status
scons: *** [wesnothd.exe] Error 1
scons: building terminated because of errors.

Former-commit-id: 46b78cbc0cd205deac4d6f591a1487a9329b072f
Former-commit-id: b40299422cd4d530376d9cf7c56ebe77ed3ba948
Former-commit-id: cce0bee619216a738620f11e8229056083322137
Former-commit-id: 8c40d87da9ea58cdb6597e170f144f9203194d65 [formerly de538c26786f4e7ca9a997567fdf2b4e4848d689]
Former-commit-id: e12d8601d565a95d09173976eef2315593b7d457