Fix strict compilation due to 2010-11-08T03:02:01Z!anonymissimus@arcor.de
Fixes the following compiler error:

src/scripting/lua.cpp:1565: error: suggest parentheses around ‘&&’ within ‘||’

I hope to have got the logic right here. Anonymissimus should confirm.


Former-commit-id: 19baab2a4e35245ff92c3bf80523a72d9ff49a2a
Former-commit-id: 2a02f262f4260fdac8a6070cb109a8b9d3f6f325
Former-commit-id: 4a37473434353c365be5b712055dbba680e53327
Former-commit-id: fc17c5bbe91faf2d6808bb1d3dd38df6c62546cc