wmllint: fix bugs with ifdef_stack
This section assumed that "#ifdef" and "#endif" would come at the very start of a line. When an author would indent the #ifdef but not the #endif, ifdef_stack.pop() would kill the starting value of None, leaving an empty list. wmllint would then crash:

  File "wmllint", line 1138, in global_sanity_check
    recruit[ifdef_stack[-1]] = (i+1, map(lambda x: x.strip(), value.split(",")))

IndexError: list index out of range

Stripping the line not only stops the crashes, but allows wmllint to pick up #ifdefs that it wasn't before.

I then looked more closely at the pop(). #endif shouldn't just drop the last value in the stack, but reset the whole stack back to None. I realized that pop() was leading to wmllint occasionally assigning recruitment that wasn't inside an #ifdef to values from earlier #ifdef stacks, e.g.:

>>  starting value: [None]
#ifdef EASY  >>  [None, 'EASY']
..
#else  >>  [None, 'EASY', '!EASY']
..
#endif  >>  pop(): [None, 'EASY']
..
recruit=  >>  ifdef_stack[-1]: EASY
Former-commit-id: 71aedd3ea5c5009adf2f502c1dcf3a0c819c6e71
Former-commit-id: b72eef26ebdc7ed2d33ffa1079cc2d3798dafcfc
Former-commit-id: 2045f3d717ebb20dd007a7b934d1f64493612a15
Former-commit-id: 729be5f39ae0417f4b02a739087a9eaa53830908 [formerly a0759ff1e6995d2a537ff6f27ab25ba2d58b62ba]
Former-commit-id: db7f1857328547928183da3a8b9b0b54a7535c36