Fix unused variable and parameter warnings from gcc
Deals with the following warnings (errors in strict mode) by removing
the offending code and dropping a parameter name, respectively.

  src/pathfind/teleport.cpp: In member function ‘void pathfind::teleport_group::get_teleport_pair(pathfind::teleport_pair&, const unit&, bool) const’:
  src/pathfind/teleport.cpp:70:12: error: variable ‘units’ set but not used [-Werror=unused-but-set-variable]

  src/pathfind/teleport.cpp:66:16: error: unused parameter ‘ignore_units’ [-Werror=unused-parameter]

iceiceice, you probably should take a look at this.


Former-commit-id: ff92ca9cdc462846cb045bac6d1a603cefb8b418
Former-commit-id: 45f79b109d79baa32e4e74ac4b569718b23837a7
Former-commit-id: 690060e909381232beb55c296bf2255623385e80
Former-commit-id: 8fadc8ac05c1b1e6911f5a49af36588a5dd5c27a [formerly 606e6b3614fdab08e180e94eee8abd5471acf845]
Former-commit-id: ce2157b976d975086bb923aef792af9ae24d714c